version: '3.1'

services:
  # server:
  #   container_name: server
  #   restart: always
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   image: server
  #   ports:
  #     - '3000:3000'
  #   expose:
  #     - '3000'
  #   env_file:
  #     - .env
  #   depends_on: 
  #     - mongo
      

  mongo:
    container_name: mongo
    restart: always
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: baedal
    volumes:
      - ./mongodb-data:/data/db

volumes:
  mongodb-data: {}

